#theme: jekyll-theme-cayman

# Site settings
title: Tech Ops Guide
name: Tech Ops Alliance # your name
email: mstechoperations@outlook.com # your email address
description: >
    Build up a technical operations knowledge base to guide the operational activities. # this means to ignore newlines until "baseurl:"
baseurl: "/techopsguide" # the subpath of your site, e.g. /blog
url: "https://mstechopsalliance.github.io" # the base hostname & protocol for your site
#twitter_username: itisbenjamin1 # your Twitter username
github_username: mstechopsalliance # your Github username
#disqus_username: itisbenjamin # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
#markdown: kramdown
